# Generated by Django 2.2.5 on 2019-09-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseGroup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=32, null=True)),
                ('ctime', models.DateField(auto_now_add=True, null=True)),
                ('uptime', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('usergroup', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TestMysql.UseGroup')),
            ],
        ),
    ]
